### PR TITLE
BootstrapTree update to handle tag tree

### PR DESCRIPTION
**Pull request by rlbabyuk**
Made changes BootstrapTree to handle tag tree, this is needed for new tests and group conversion to widgetastic.

### CODE REVIEW

**Comment by mfalesni** [comment]
@rlbabyuk DId you check it against trees in CFME? Does it still work with normal trees?

**Comment by rlbabyuk** [comment]
@mfalesni As I found, we are using this tree also in ManageIQTree, so I've tested it with my changes for catalog_items tests. Tests work fine.

**Comment by mfalesni** [comment]
@rlbabyuk  Good. I will need to build a test page(s) for the widgets so we can have some sort of unit tests around that :) I will merge this, please keep an eye on the trees or complints about trees in following days.

**Comment by rlbabyuk** [comment]
@mfalesni sure, thanks:)

**Pull request merged**
